version: '3.8'

services:

  mail:
    build:
      context: "./mail"
      dockerfile: "Dockerfile"
    ports:
      - "${SMTP_PORT-1025}:${SMTP_PORT-1025}"
      - "${SMTP_GUI_PORT-8025}:${SMTP_GUI_PORT-8025}"

  database:
    build:
      context: "./database"
      dockerfile: "Dockerfile"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT-5432}:${POSTGRES_PORT-5432}"

  backend:
    build:
      context: "./backend"
      dockerfile: "Dockerfile"
    depends_on:
      - database
    env_file:
      - ".env"
    volumes:
      - "./backend:/app"
    ports:
      - "${SERVER_PORT-5000}:${SERVER_PORT-5000}"

  frontend:
    build:
      context: "./frontend"
      dockerfile: "Dockerfile"
    volumes:
      - "./frontend:/app"
    environment:
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true
    ports:
      - "4200:4200"
