"""add is_logged_out column to user table

Revision ID: 12b2cce532b5
Revises: 4569c31b2be6
Create Date: 2024-09-19 10:16:28.102465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b2cce532b5'
down_revision: Union[str, None] = '4569c31b2be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_logged_out', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_logged_out')
    # ### end Alembic commands ###
