"""add otp feature to user table

Revision ID: 672fac2f63bd
Revises: 12b2cce532b5
Create Date: 2024-09-19 15:20:38.369437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '672fac2f63bd'
down_revision: Union[str, None] = '12b2cce532b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_enable_otp', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('otp_secret', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('otp_recovery', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_recovery')
    op.drop_column('users', 'otp_secret')
    op.drop_column('users', 'is_enable_otp')
    # ### end Alembic commands ###
